### ISSUE TITLE
Error en index.md

### ISSUE THREAD

**Issue by alu0100505078** [DanielRamosAcosta/rafa-daniel-pedro-dsi1516#1]
En la línea 57 del archivo [index.md](https://github.com/DanielRamosAcosta/rafa-daniel-pedro-dsi1516/blob/master/index.md),  hay una falta ortográfica. En vez de escribir framework se ha escrito framwork.

**Comment by DanielRamosAcosta** [comment]
Cierto, y también multiágina en vez de multipágina.

**Comment by DanielRamosAcosta** [comment]
Corregido en el commit 51c10c57af4f2b0968ddee94d5900239fa1e37c5.
